version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      APP_ENV: dev
      HTTP_PORT: "8080"
      DATABASE_URL: postgres://app:app@db:5432/app?sslmode=disable
      JWT_ACCESS_SECRET: dev-access-secret-change-me
      JWT_REFRESH_SECRET: dev-refresh-secret-change-me
      MASTER_KEY: 01234567890123456789012345678901
    ports:
      - "8080:8080"
volumes:
  pgdata: {}
