services:
  - type: web
    name: learningyogi-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: learningyogi-db
          property: connectionString
    autoDeploy: false

databases:
  - name: learningyogi-db
    databaseName: learningyogi
    user: learningyogi_user
    plan: free
